---
title: Digital Media Portfolio
timezone: America/New_York
collections:
  posts:
    title: Posts
    output: true
  projects:
    title: Projects
    output: true
  uploads:
    title: Uploads
    output: true
author: Ethan Turkeltaub
permalink: pretty
