---
title: Digital Media Portfolio
url: http://digitalmedia.ethnt.me
timezone: America/New_York
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
  work:
    title: Work
    output: true
permalink: pretty
